FROM python:3.12-rc-slim

WORKDIR /app

COPY ./app /app/src
COPY requirements.txt /app

RUN pip install -r requirements.txt

EXPOSE 5000

CMD [ "export", "FLASK_APP=src/app.py", "&&", "flask", "run"]
